version: '3.8'

services:
  drian:
    build: .
    container_name: drian
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
