version: '3.8'

services:
  meu-site:
    build: .
    container_name: drian
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
