version: '3.8'

services:
  meu-site:
    build: .
    container_name: drian
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - proxy

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
